apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: vsphere-csi.community.tanzu.vmware.com.2.6.2
spec:
  refName: vsphere-csi.community.tanzu.vmware.com
  version: 2.6.2
  releaseNotes: "vsphere-csi 2.6.2 https://github.com/kubernetes-sigs/vsphere-csi-driver/releases/tag/v2.6.2"
  licenses:
    - "Apache 2.0"
  template:
    spec:
      fetch:
        - imgpkgBundle:
            image: projects.registry.vmware.com/tce/vsphere-csi@sha256:0263aa6982f3d36bf94bc0a97b279873e2ab975ed5cbc751ad86acd05e92a5ff
      template:
        - ytt:
            paths:
              - config/
        - kbld:
            paths:
              - "-"
              - .imgpkg/images.yml
      deploy:
        - kapp: {}
